name: Sentinel
on: [push]
strategy:
  matrix:
    python-version: [3.7, 3.8, 3.9]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install -r requirements.txt
      - run: make lint
      - run: make test